title: Phil Malle
subtitle: Cyber-Security || Technologies || Pen-Testing || Hacking (Ethical)
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog about technologies, Cyber-Security and other similar topics. 

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About Me
      url: /about
    - text: Achievements
      url: /gallery
    - text: Blog
      url: /blog
    - text: Contact
      url : /contact
    - text: Links
      url: /links
    - text: PGP-Public-Key
      url: /pgp


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Phil Malle
author_bio: Hi, my name is Phil Malle. This is my personal blog about technologies, Cyber-Security and other similar topics.
author_email: "philipp.malle@pm.com"
author_location: Austria
author_website_url: "https://philmalle.github.io"
typewrite-text: Cyber-Security || Technologies || Pen-Testing || Hacking

# Experiences
author_work_experiences:
            - company_name: Atos
              company_logo: atos.png
              company_url: https://atos.net
              designation: Cyber Security Analyst
              description: SOC Analyst
              visibility: true
            - company_name: Atos
              company_logo: atos.png
              company_url: https://atos.net
              designation: Network Engineer
              description: Configured and operate Campus-LAN based on Cisco Hardware
              visibility: true

# Education
author_education_details:
              - college_logo: ccna-rs.png
                college_name: CCNA
                college_url: https://www.credly.com/badges/352a61de-48a9-4fe8-9c1e-82b52fd094a6/public_url
                college_degree: Cisco Certified Network Associate Routing and Switching 
                description: Expires on 30 April 2023
                visibility: true
              - college_logo: ccna-s.png
                college_name: CCNA
                college_url: https://www.credly.com/badges/3d4020c8-a8fe-415f-b811-cde350ffef7b/public_url
                college_degree: Cisco Certified Network Associate Security 
                description: Expires on 30 April 2023
                visibility: true
              - college_logo: specialist.png
                college_name: CCNA
                college_url: https://www.credly.com/badges/3d4020c8-a8fe-415f-b811-cde350ffef7b/public_url
                college_degree: Cisco Certified Specialist - Data Center Design 
                description: Expires on 9 February 2022
                visibility: true


# Projects
author_project_details:
              - project_thumbnail: BlueteamlabsOnline.png
                project_title: BlueTeamLabs
                project_description: A Platform for Cyber Defense
                project_url: https://blueteamlabs.online
                visibility: true
              - project_thumbnail: HackTheBox.jpg
                project_title: HackTheBox
                project_description: A Platform for Hacking
                project_url: https://hackthebox.eu
                visibility: true
              - project_thumbnail: THMlogo.jpg
                project_title: TryHackMe
                project_description: A Platform for Hacking
                project_url: https://tryhackme.com
                visibility: true

# social links
twitter_username: phil_malle
github_username:  philmalle
facebook_username: malle.philipp
linkedin_username: phil-malle
behance_username: 
instagram_username: phil.malle
medium_username: 
telegram_username: PMalle
discord_username: Fr3akazo1d#4082
dribbble_username: 
flickr_username: 


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: philmalle

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
#getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
